package com.milkbasket.rest.services.push.common.bean;

import java.io.Serializable;

import javax.validation.constraints.Null;

import com.milkbasket.core.framework.validator.annotation.IsFlag;
import com.milkbasket.core.framework.validator.annotation.Mandatory;
import com.milkbasket.core.framework.validator.annotation.MaxLength;
import com.milkbasket.core.framework.validator.annotation.MinLength;
import com.milkbasket.core.framework.validator.annotation.ValidColumnValue;
import com.milkbasket.core.framework.websupport.base.BaseBean;

import com.milkbasket.rest.services.communication.entity.DeviceConstants.Device;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Bean to be returned with device related information.
 *
 * @author iTuple
 * @version $Id: $Id
 */
@ApiModel(description = "Device Response.")
public class DeviceBean extends BaseBean implements Serializable {

	private static final long serialVersionUID = 201808291936360533L;

	@ApiModelProperty(value = "Autogenerated Database ID. Not Required in input field while save or update.", readOnly = true)
	@Null
	private Long id;

	@ApiModelProperty(value = "Customer id with which basket is associated. Mandatory input field. Accept numeric characters only.", allowEmptyValue = false)
	@ValidColumnValue(table = "customers", column = "id")
	@Mandatory
	private Long customerId;

	@ApiModelProperty(value = "Operating system of device. Mandatory input field.", allowEmptyValue = false)
	@Mandatory
	private Device deviceOs;

	@ApiModelProperty(value = "Push Id associated with device. Mandatory input field. Accept numeric characters only.", allowEmptyValue = false)
	@Mandatory
	private String pushId;

	@ApiModelProperty(value = "UDID associated with device. Mandatory input field.", allowEmptyValue = false)
	@Mandatory
	@MinLength(length = 1)
	@MaxLength(length = 45)
	private String udid;

	@ApiModelProperty(value = "Is device logout. Mandatory input field. Accept numeric characters only.", allowEmptyValue = false)
	@Mandatory
	@IsFlag
	private Integer deviceLogout;

	/**
	 * <p>
	 * Setter for the field <code>id</code>.
	 * </p>
	 *
	 * @param id
	 *            a {@link java.lang.Long} object.
	 */
	public void setId(final Long id) {
		this.id = id;
	}

	/**
	 * <p>
	 * Getter for the field <code>id</code>.
	 * </p>
	 *
	 * @return Autogenerated Database ID. Not Required in Input Field while save or
	 *         update
	 */
	public Long getId() {
		return id;
	}

	/**
	 * <p>
	 * Setter for the field <code>customerId</code>.
	 * </p>
	 *
	 * @param customerId
	 *            a {@link java.lang.Long} object.
	 */
	public void setCustomerId(final Long customerId) {
		this.customerId = customerId;
	}

	/**
	 * <p>
	 * Getter for the field <code>customerId</code>.
	 * </p>
	 *
	 * @return Customer id with which basket is associated.
	 */
	public Long getCustomerId() {
		return customerId;
	}

	/**
	 * <p>
	 * Getter for the field <code>deviceOs</code>.
	 * </p>
	 *
	 * @return a
	 *         {@link com.milkbasket.rest.services.push.common.entity.DeviceConstants.Device}
	 *         object.
	 */
	public Device getDeviceOs() {
		return deviceOs;
	}

	/**
	 * <p>
	 * Setter for the field <code>deviceOs</code>.
	 * </p>
	 *
	 * @param deviceOs
	 *            a
	 *            {@link com.milkbasket.rest.services.push.common.entity.DeviceConstants.Device}
	 *            object.
	 */
	public void setDeviceOs(final Device deviceOs) {
		this.deviceOs = deviceOs;
	}

	/**
	 * <p>
	 * Setter for the field <code>pushId</code>.
	 * </p>
	 *
	 * @param pushId
	 *            a {@link java.lang.String} object.
	 */
	public void setPushId(final String pushId) {
		this.pushId = pushId;
	}

	/**
	 * <p>
	 * Getter for the field <code>pushId</code>.
	 * </p>
	 *
	 * @return Push Id associated with device.
	 */
	public String getPushId() {
		return pushId;
	}

	/**
	 * <p>
	 * Setter for the field <code>udid</code>.
	 * </p>
	 *
	 * @param udid
	 *            a {@link java.lang.String} object.
	 */
	public void setUdid(final String udid) {
		this.udid = udid;
	}

	/**
	 * <p>
	 * Getter for the field <code>udid</code>.
	 * </p>
	 *
	 * @return UDID associated with device
	 */
	public String getUdid() {
		return udid;
	}

	/**
	 * <p>
	 * Setter for the field <code>deviceLogout</code>.
	 * </p>
	 *
	 * @param deviceLogout
	 *            a {@link java.lang.Integer} object.
	 */
	public void setDeviceLogout(final Integer deviceLogout) {
		this.deviceLogout = deviceLogout;
	}

	/**
	 * <p>
	 * Getter for the field <code>deviceLogout</code>.
	 * </p>
	 *
	 * @return Is device logout.
	 */
	public Integer getDeviceLogout() {
		return deviceLogout;
	}

	/**
	 * <p>
	 * newInstance.
	 * </p>
	 *
	 * @return a {@link com.milkbasket.rest.services.push.common.bean.DeviceBean}
	 *         object.
	 */
	public static DeviceBean newInstance() {
		return new DeviceBean();
	}
}
